version: '3'

services:
  gateway:
    image: traefik:v2.5
    command: --configFile=/etc/traefik/traefik.yml
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik-dynamic-conf.yml:/etc/traefik/traefik-dynamic-conf.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web

  hello:
    build: 
      context: hello
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000"
    networks:
      - web
  world:
    build: 
      context: world
      dockerfile: Dockerfile
    # ports:
    #   - "5001:5001"
    networks:
      - web
  time:
    build: 
      context: time
      dockerfile: Dockerfile
    # ports:
    #   - "5002:5002"
    networks:
      - web
  client:
    build: 
      context: client
      dockerfile: Dockerfile
    # ports:
    #   - "5003:5003"
    networks:
      - web

networks:
  web:
    external: true
