version: "3.9"

services:
  kong-db:
    image: postgres:9.6
    container_name: kong-db
    restart: on-failure
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3

  kong-migrations:
    image: kong:2.6.0
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong

  kong:
    image: kong:2.6.0
    container_name: kong
    restart: on-failure
    depends_on:
      - kong-db
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000/tcp"
      - "8443:8443/tcp"
      - "8001:8001/tcp"
      - "8444:8444/tcp"

  konga:
    image: pantsel/konga
    container_name: konga
    restart: on-failure
    depends_on:
      - kong-db
      - kong-migrations
      - kong
    environment:
      DB_ADAPTER: postgres 
      DB_HOST: kong-db 
      DB_USER: kong 
      DB_PASSWORD: kong 
      DB_DATABASE: kong 
      NODE_ENV: production 
    ports:
     - "1337:1337"
